notifications:
  slack: wtsi-cgpit:ptUMR1tkNyZJYd9TpGoss8WR
  email: false

sudo: false

language: ruby

services:
  - docker

script:
  - set -e
  - echo 'Build and check docker image'
  - docker build -t vcfflagmodifier .
  - docker images | grep -c vcfflagmodifier
  - echo 'Verify program(s) from this repo'
  - docker run -t --rm vcfflagmodifier vcf_flag_modifier.py --version
